services:

  finsight-api:

    build: .

    container_name: finsight-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./agents/ml_prediction_agent/model_store:/app/agents/ml_prediction_agent/model_store
      - ./rag/vector_store:/app/rag/vector_store